In [1]:
!pip install requests

!pip install requests -U

Requirement already satisfied: requests in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (2022.9.24)
Requirement already satisfied: requests in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dmlpz\anaconda3\envs\greg\lib\site-packages (from requests) (2022.9.24)

In [2]:
from shapely.wkt import loads
import pandas as pd
import spacy
import nltk
nlp=spacy.load('en_core_web_sm')

nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [3]:
import csv
import requests
import geopandas as gpd

## Texas' Counties and Cities

In [7]:
texasrequest = requests.get("https://data.texas.gov/resource/m3yf-ffwm.json")

#load data as text
texasner = texasrequest.text

#load data as GeoDataFrame
texasnerdf = pd.read_csv('https://data.texas.gov/api/views/m3yf-ffwm/rows.csv?accessType=DOWNLOAD&api_foundry=true')

In [8]:
texasnerdf.head()

,the_geom,SOURCE,STRATMAP_I,LOCAL_ID,NAME,FIPS_CODE,TXDOT_ABBR,COG_ABBR,DATE_CREAT,DATE_MODIF,DATE_RETIR,SHAPE_Leng,SHAPE_Area
0,MULTIPOLYGON (((-102.5396299999994 36.05514000...,DRG,NaN,113,Dallam,111,4,113,01/01/1964 08:00:00 AM +0000,NaN,NaN,2.647739,0.391036
1,MULTIPOLYGON (((-101.62343999999949 36.0553899...,DRG,NaN,113,Sherman,421,4,113,01/01/1963 08:00:00 AM +0000,NaN,NaN,1.968011,0.239757
2,MULTIPOLYGON (((-101.08517000000039 36.4998599...,DRG,NaN,113,Hansford,195,4,113,01/01/1973 08:00:00 AM +0000,NaN,NaN,1.965535,0.239188
3,MULTIPOLYGON (((-100.54607000000041 36.4595700...,DRG,NaN,113,Ochiltree,357,4,113,01/01/1972 08:00:00 AM +0000,NaN,NaN,1.967331,0.238828
4,MULTIPOLYGON (((-100.54019999999956 36.0559900...,DRG,NaN,113,Lipscomb,295,4,113,01/01/1972 08:00:00 AM +0000,NaN,NaN,1.979816,0.242397

In [9]:
texasnerdf.dtypes

the_geom       object
SOURCE         object
STRATMAP_I    float64
LOCAL_ID        int64
NAME           object
FIPS_CODE       int64
TXDOT_ABBR      int64
COG_ABBR        int64
DATE_CREAT     object
DATE_MODIF    float64
DATE_RETIR    float64
SHAPE_Leng    float64
SHAPE_Area    float64
dtype: object

In [19]:
texasnerdf['geometry'] = texasnerdf['the_geom']
texasnerdf.geometry =  texasnerdf['the_geom'].apply(loads)
#texasgdf = gpd.GeoDataFrame(texasnerdf)

texasnerdf.dtypes

the_geom       object
SOURCE         object
STRATMAP_I    float64
LOCAL_ID        int64
NAME           object
FIPS_CODE       int64
TXDOT_ABBR      int64
COG_ABBR        int64
DATE_CREAT     object
DATE_MODIF    float64
DATE_RETIR    float64
SHAPE_Leng    float64
SHAPE_Area    float64
geometry       object
dtype: object

In [50]:
texasnerdf.loc[:,["NAME","geometry"]]

          NAME                                           geometry
0       Dallam  (POLYGON ((-102.5396299999994 36.0551400000004...
1      Sherman  (POLYGON ((-101.6234399999995 36.0553899999995...
2     Hansford  (POLYGON ((-101.0851700000004 36.4998599999999...
3    Ochiltree  (POLYGON ((-100.5460700000004 36.4595700000009...
4     Lipscomb  (POLYGON ((-100.5401999999996 36.0559900000007...
..         ...                                                ...
249     Crosby  (POLYGON ((-101.0388100000001 33.3971500000007...
250    Dickens  (POLYGON ((-101.0412500000003 33.8336299999992...
251       King  (POLYGON ((-100.0485599999994 33.8359799999998...
252     Yoakum  (POLYGON ((-102.5946999999997 33.3883399999995...
253      Garza  (POLYGON ((-101.1734199999993 32.9635999999991...

[254 rows x 2 columns]

## Text Aanalysis Named Enities Reconginzation

In [4]:
text = open('../Corridos/corrido corpus/ElCorridodeGregorioCortez_X.txt', encoding="utf-8").read()
for number, sentence in enumerate(nltk.sent_tokenize(text)):
    print(sentence)
 # Break text into sentences
sentences = nltk.sent_tokenize(text)

In the country of Karnes,
Look what has happened;
The Major Sheriff died,
Leaving Román badly wounded.
It must have been two in the
	afternnon
When people arrived;
They said to one another,
“It is not known who killed him.”

They went around asking questions,
About half an hour afterward,
They found that the wrongdoer
Had been Gregorio Cortez.
Now they have outlawed Cortez,
Throughout the whole state;
Let him be taken, dead or alive;
He has killed several men.
They said Gregorio Cortez,
With his pistol in his hand,
“I don’t regret that I killed him;
I regret my brother’s death.”

Then said Gregorio Cortez,
And his soul was all aflame,
“I don’t regret that I killed him;
A man must defend himself.”

The Americans were coming,
They were whiter than a dove,
From the fear that they had
Of Cortez and of his pistol.
Then the Americans said,
Then they said fearfully,
“Come, let us follow the trail;
The wrongdoer is Cortez.”

They set the bloodhounds on him,
So they could follow his trail,
But trying to overtake  Cortez
Was like following a star..
He struck out for Gonzales
Without showing any fear,
“Follow me, cowardly rangers,
I am Gregorio Cortez.”

From Belmont he went to the
	ranch,
They succeeded in surrounding
	him,
Quite a few more than three hundred,
But there he jumped their corral.
When he jumped their corral,
According to what we hear,
They got into a gunfight,
And he killed them another sheriff,

Then said Gregorio Cortez,
With his pistol in his hand,
“Don’t run, you cowardly rangers,
From just one Mexican.”

Gregorio Cortez went out,
He went towards Laredo
They decided not to follow
Because they were afraid of him.
Then said Gregorio Cortez,
“What is the use of your scheming?
You cannot catch me,
Even with those bloodhounds.”

Then the Americans said,
“If we catch you with him, what
Shall we do?
If we fight him man to man,
Very few of us will return.”

Over by El Encinal,
According to what we hear,
They made him a corral,
And he killed them another sheriff.
Then said Gregorio Cortez,
Shooting out a lot of bullets,
“I have weathered thunderstorms;
This little mist doesn’t bother me.”

Now he has met a Mexican;
He says to him haughtily,
“Tell me the news;
I am Gregorio Cortez.”

“It is said that because of me
Many people have been killed;
I will surrender now
Because such things are not right.”

Cortez says to Jesús,
“At last you are going to see it;
Go tell the rangers
To come and arrest me.”

All the rangers were coming,
Coming so fast they even flew,
For they wanted to get
The thousand dollars they were
offered.
When they surrounded the house,
Cortez suddenly appeared before
	them,
“You will take me if I’m willing,
But not any other way.”

Then the Major Sheriff said,
As if he was going to cry,
“Cortez, hand over your weapons;
We are not going to kill.”

Then said Gregorio Cortez,
Shouting to them in a loud voice,
“I won’t surrender my arms
Until I am in a cell.”

Then said Gregorio Cortez,
He said in his godly voice,
“I won’t surrender my arms
Until I’m inside a jail.”

Now they have taken Cortez,
Now matters are at an end,
His poor family
Are suffering in their hearts.
Now with this I say farewell,
In the shade of a cypress treel;
This the end of singing
Of the ballad of Cortez.

In [5]:
doc =nlp(text)

for ent in doc.ents:
    print (ent.text, ent.label_)

Karnes ORG
two CARDINAL
About half an hour TIME
Gregorio Cortez PERSON
Cortez ORG
Gregorio Cortez PERSON
Gregorio Cortez PERSON
Americans NORP
Cortez ORG
Americans NORP
Cortez ORG
Cortez ORG
Gonzales PERSON
Gregorio Cortez PERSON
Belmont GPE
more than three hundred CARDINAL
Gregorio Cortez PERSON
just one CARDINAL
Mexican NORP
Laredo ORG
Gregorio Cortez PERSON
Americans NORP
Shall PERSON
El Encinal ORG
Gregorio Cortez PERSON
Mexican NORP
Gregorio Cortez PERSON
Jesús ORG
The thousand dollars MONEY
Cortez ORG
Cortez ORG
Gregorio Cortez PERSON
Gregorio Cortez PERSON
Cortez ORG
Cortez ORG

In [6]:
# Getting the pipeline component
ner=nlp.get_pipe("ner")